<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastsMessages($nbMax = 50)
    {
        $q = $this->createQueryBuilder('m')
                  ->leftJoin('m.user', 'u')
                  ->addSelect('u')
                  ->setMaxResults($nbMax)
                  ->orderBy('m.date', 'asc');

        return $q->getQuery()->getResult();
    }
}
