<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastsMessages($nbMax = 50)
    {
        $q = $this->createQueryBuilder('m')
                  ->leftJoin('m.user', 'u')
                  ->addSelect('u')
                  ->orderBy('m.date', 'desc')
                  ->setMaxResults($nbMax);

        return array_reverse($q->getQuery()->getResult());
    }
}
