# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    micro_chat.chat_manager:
        class: AppBundle\Chat\ChatManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
            - "@security.token_storage"

    micro_chat.login_redirection_handler:
        class: AppBundle\Redirection\AfterLoginRedirection
        arguments:
            - "@router"
            - "@micro_chat.chat_manager"

    micro_chat.logout_redirection_handler:
        class: AppBundle\Redirection\AfterLogoutRedirection
        arguments:
            - "@router"
            - "@security.token_storage"
            - "@micro_chat.chat_manager"